name: Commands

on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hola"
      - name: multiline script
        run: |
          node -v
          npm -v